-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."contests" add column "end_at" Timestamp
--  not null default now();
