-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."contests" add column "voting_start_at" timestamptz
--  not null default now();
