-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."contest_entries_votes" add column "updated_at_round" integer
--  null;
