-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."collections_analytics_1d" add column "total_items" integer
--  null;
